server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:~/test;MODE=POSTGRESQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        highlight_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    jdbc:
      initialize-schema: never  # schema.sql로 관리하므로 자동 생성 비활성화