spring:
  application:
    name: SB03-Deokhugam-Team3
  profiles:
    active: test

# S3 - 테스트용 더미
deokhugam:
  storage:
    type: s3
    s3:
      access-key: dummy-access-key
      secret-key: dummy-secret-key
      region: dummy-region
      bucket: dummy-bucket
      presigned-url-expiration: 600