spring:
  application:
    name: SB03-Deokhugam-Team3
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# OCR 구현체 설정
ocr:
  vision:
    enabled: false # Google Cloud Vision API 사용 여부
  tesseract:
    enabled: true # Tesseract

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# S3
deokhugam:
  storage:
    type: ${STORAGE_TYPE:s3}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

# Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method