spring:
  application:
    name: SB03-Deokhugam-Team3
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method